twig:
    paths: ['%kernel.project_dir%/views']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        menuservice: '@App\Service\MenuService'
        settingservice: '@App\Service\SettingService'
        fileservice: '@App\Service\FileService'
    form_themes: ['bootstrap_4_layout.html.twig']
