twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        blockservice: '@App\Service\BlockService'
        menuservice: '@App\Service\MenuService'
        settingservice: '@App\Service\SettingService'
        fileservice: '@App\Service\FileService'
        templateservice: '@App\Service\TemplateService'
        permissionservice: '@App\Service\UserPermissionService'
    form_themes: ['bootstrap_4_layout.html.twig']
