version: '3.8'

services:
    apache:
        build:
            context: .
            dockerfile: Dockerfile-Apache
        volumes:
            - ./:/var/www/html/
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/
        ports:
            - 80:80
        networks:
            - frontend
            - backend

    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: Dsd255255
        ports:
            - 3306:3306
        volumes:
            - ./var/data/mariadb/:/var/lib/mysql
        networks:
            - backend

    memcached:
        image: memcached
        ports:
            - 11211:11211
        networks:
            - backend

    nodejs:
        build:
            context: .
            dockerfile: Dockerfile-Nodejs
        ports:
            - 3000:8080
        networks:
            - frontend

    redis:
        image: redis
        volumes:
            - ./var/data/redis/:/data
        networks:
            - frontend

networks:
    frontend:
    backend:
