FROM php:7.4-apache
RUN apt-get update && apt-get install -y
RUN apt-get install -y git
RUN apt-get install -y zip
RUN docker-php-ext-install pdo pdo_mysql
RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN a2enmod rewrite
RUN apt-get install -y zlib1g-dev\
    libmemcached11 \
    libmemcachedutil2 \
    build-essential \
    libmemcached-dev
RUN pecl install memcached
RUN echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini
