actions:
    list:
        name: Discount codes
        api: /discount-code/list/
        permissions: ['admin_discount_code_list', 'api_discount_code_list']
        roles: ['superadmin']

    get:
        name: View discount code
        api: /discount-code/get/
        permissions: ['admin_discount_code_list', 'api_discount_code_list', 'api_discount_code_info']
        roles: ['superadmin']

    insert:
        name: Create discount code
        api: /discount-code/insert/
        permissions: ['admin_discount_code_insert', 'api_discount_code_insert']
        roles: ['superadmin']

    update:
        name: Update discount code
        api: /discount-code/update/
        permissions: ['admin_discount_code_update', 'api_discount_code_update', 'api_discount_code_info']
        roles: ['superadmin']

    delete:
        screen: discount-code/
        api: /etting/delete/
        name: Delete discount code
        permissions: ['api_discount_code_delete', 'api_discount_code_delete_multiple']
        roles: ['superadmin']

fields:
    id:
        id: id
        label: id
        type: int
        required: true
        editable: false
        list: true
        form: false
        translate: false
    description:
        id: description
        label: description
        type: text
        required: true
        editable: true
        list: true
        form: true
        translate: false
    code:
        id: code
        label: code
        type: text
        required: true
        editable: true
        list: true
        form: true
        translate: false
    startDate:
        id: startDate
        label: start_date
        type: date
        editable: true
        list: true
        form: true
        translate: false
    endDate:
        id: endDate
        label: end_date
        type: date
        editable: true
        list: true
        form: true
        translate: false
    price:
        id: price
        label: price
        type: price
        editable: true
        list: true
        form: true
        translate: false
    percentage:
        id: percentage
        label: percentage
        type: integer
        editable: true
        list: true
        form: true
        translate: false
    active:
        id: active
        label: active
        type: switch
        editable: true
        list: true
        form: true
        translate: false
