actions:
    list:
        name: Subscriptions
        api: /subscription/list/
        permissions: ['admin_subscription_list', 'api_subscription_list']
        roles: ['superadmin']

    get:
        name: View subscription
        api: /subscription/get/
        permissions: ['admin_subscription_list', 'api_subscription_list', 'api_subscription_info']
        roles: ['superadmin']

    insert:
        name: Create subscription
        api: /subscription/insert/
        permissions: ['admin_subscription_insert', 'api_subscription_insert']
        roles: ['superadmin']

    update:
        name: Update subscription
        api: /subscription/update/
        permissions: ['admin_subscription_update', 'api_subscription_update', 'api_subscription_info']
        roles: ['superadmin']

    delete:
        screen: subscription/
        api: /subscription/delete/
        name: Delete subscription
        permissions: ['api_subscription_delete', 'api_subscription_delete_multiple']
        roles: ['superadmin']

fields:
    id:
        id: id
        label: id
        type: int
        required: true
        editable: false
        list: true
        form: false
        translate: false
    title:
        id: title
        label: title
        type: text
        required: true
        editable: true
        list: true
        form: true
        translate: false
    description:
        id: description
        label: description
        type: textarea
        editable: true
        list: true
        form: true
        translate: false
    price:
        id: price
        label: price
        type: price
        required: true
        editable: true
        list: true
        form: true
        translate: false
    term:
        id: term
        label: interval
        type: select
        options: [ { value: 1w, text: weekly }, { value: 2w, text: every_week }, { value: 1m, text: every_month }, { value: 3m, text: every_quarter }, { value: 6m, text: every_half_year }, { value: 12m, text: every_year } ]
        required: true
        editable: true
        list: true
        form: true
        translate: false
    vat:
        id: vat
        label: vat
        type: selectfilter
        options_source: /vat/list/
        option_key: id
        option_value: title
        required: true
        editable: true
        list: true
        form: true
        translate: false
    active:
        id: active
        label: active
        type: switch
        required: false
        editable: true
        list: true
        form: true
        translate: false
