actions:
    list:
        name: User subscription
        api: /user-subscription/list/
        permissions: ['admin_user_subscription_list', 'api_user_subscription_list']
        roles: ['superadmin']

    get:
        name: View user subscription
        api: /user-subscription/get/
        permissions: ['admin_user_subscription_list', 'api_user_subscription_list', 'api_user_subscription_info']
        roles: ['superadmin']

    insert:
        name: Create user subscription
        api: /user-subscription/insert/
        permissions: ['admin_user_subscription_insert', 'api_user_subscription_insert']
        roles: ['superadmin']

    update:
        name: Update user subscription
        api: /user-subscription/update/
        permissions: ['admin_user_subscription_update', 'api_user_subscription_update', 'api_user_subscription_info']
        roles: ['superadmin']

    delete:
        screen: user-subscription/
        api: /user-subscription/delete/
        name: Delete user subscription
        permissions: ['api_user_subscription_delete', 'api_user_subscription_delete_multiple']
        roles: ['superadmin']

fields:
    id:
        id: id
        label: id
        type: int
        required: true
        editable: false
        list: true
        form: false
        translate: false
    user:
        id: user
        label: user
        type: select
        required: true
        editable: false
        list: true
        form: true
        translate: false
    subscription:
        id: subscription
        label: subscription
        type: select
        editable: false
        list: true
        form: true
        translate: false
    startDate:
        id: startDate
        label: start_date
        type: date
        editable: true
        list: true
        form: true
        translate: false
    endDate:
        id: endDate
        label: end_date
        type: date
        editable: true
        list: true
        form: true
        translate: false
    active:
        id: active
        label: active
        type: switch
        required: false
        editable: true
        list: true
        form: true
        translate: false
