#index:
#    path: /{_locale}/
#    controller: App\Controller\DefaultController::index
freelancer_admin:
    path: /{_locale}/admin/freelancer
    controller: Freelancer\Controller\FreelancerController::list
    requirements:
        _locale: '%app.locales%'

file:
    path: /{_locale}/file/{file}
    controller: App\Controller\FileController::index
    requirements:
        page: '\d+'
        _locale: '%app.locales%'

logout:
    path: /{_locale}/logout
    requirements:
        _locale: '%app.locales%'
