#index:
#    path: /{_locale}/
#    controller: App\Controller\DefaultController::index
freelancer_admin:
    path: /{_locale}/admin/freelancer
    controller: Freelancer\Controller\FreelancerController::list
    requirements:
        _locale: '%app.locales%'
